using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
        using System.Globalization;
        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;

namespace proyect.Models
{// <auto-generated />
 //
 // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
 //
 //    using QuickType;
 //
 //    var welcome = Welcome.FromJson(jsonString);



    public partial class Welcome
    {
        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("terms")]
        public Uri Terms { get; set; }

        [JsonProperty("privacy")]
        public Uri Privacy { get; set; }

        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("quotes")]
        public Quotes Quotes { get; set; }
    }

    public partial class Quotes
    {
        [JsonProperty("USDEUR")]
        public double UsdEur { get; set; }

        [JsonProperty("USDUSD")]
        public double UsdUsd { get; set; }
    }

    public partial class Welcome
    {
        public static Welcome FromJson(string json) => JsonConvert.DeserializeObject<Welcome>(json, proyect.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Welcome self) => JsonConvert.SerializeObject(self, proyect.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            }
        };


    } 
}

