//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsAcciones
    {
        public int Id { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Accion { get; set; }
        public string Entidad { get; set; }
        public Nullable<int> EntidadId { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
