//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesPermisos
    {
        public int RolId { get; set; }
        public int PermisoId { get; set; }
        public int rolPermisoId { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Permisos Permisos { get; set; }
    }
}
