//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public int Id { get; set; }
        
        
        [Required(ErrorMessage = "El nombre es obligatorio")]
        [StringLength(100)]
        public string Nombre { get; set; }


            [Required(ErrorMessage = "El email es obligatorio")]
            [StringLength(100)]
            [EmailAddress(ErrorMessage = "El formato del email no es válido")]
            public string Email { get; set; }

        [Required(ErrorMessage = "La contraseña es obligatoria")]
        [StringLength(255)]
        public string Contrasena { get; set; }
        [Required(ErrorMessage = "El rol es obligatorio")]
        public int RolID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
